In [40]:
import pandas as pd
import numpy as py
import datetime as dt

In [41]:
# defining the file path
filepath = "2018weatherdata_csv.csv"
filepath

'2018weatherdata_csv.csv'

In [42]:
# Open the file
weather_df = pd.read_csv(filepath)

In [43]:
weather_df.head()

,USAF,WBAN,YR--MODAHRMN,DATE,DIR,SPD,GUS,CLG,SKC,L,...,SLP,ALT,STP,MAX,MIN,PCP01,PCP06,PCP24,PCPXX,SD
0,724030,93738,201801000000,2018-01-01,***,0,***,722,SCT,*,...,1030,*****,1018,21,13,*****,0,*****,*****,**
1,724030,93738,201801000000,2018-01-01,320,5,***,722,SCT,*,...,1030,30,1018,***,***,0,*****,*****,*****,**
2,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,*,...,1031,30,1018,***,***,0,*****,*****,*****,**
3,724030,93738,201801000000,2018-01-01,990,3,***,722,CLR,*,...,1031,30,1018,***,***,0,*****,*****,*****,**
4,724030,93738,201801000000,2018-01-01,320,6,***,722,CLR,*,...,1031,30,1019,***,***,0,*****,*****,*****,**

In [44]:
# Drop columns with no data
del weather_df['L']
del weather_df['M']
del weather_df['H']
del weather_df['MW']
del weather_df['MW_1']
del weather_df['MW_2']
del weather_df['MW_3']
del weather_df['AW']
del weather_df['AW_4']
del weather_df['AW_5']
del weather_df['AW_6']
del weather_df['W']
del weather_df['PCP01']
del weather_df['PCP06']
del weather_df['PCP24']
del weather_df['PCPXX']
del weather_df['SD']

In [45]:
weather_df.head()

,USAF,WBAN,YR--MODAHRMN,DATE,DIR,SPD,GUS,CLG,SKC,VSB,TEMP,DEWP,SLP,ALT,STP,MAX,MIN
0,724030,93738,201801000000,2018-01-01,***,0,***,722,SCT,10,14,6,1030,*****,1018,21,13
1,724030,93738,201801000000,2018-01-01,320,5,***,722,SCT,10,15,8,1030,30,1018,***,***
2,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,11,6,1031,30,1018,***,***
3,724030,93738,201801000000,2018-01-01,990,3,***,722,CLR,10,11,4,1031,30,1018,***,***
4,724030,93738,201801000000,2018-01-01,320,6,***,722,CLR,10,13,3,1031,30,1019,***,***

In [46]:
# Drop the rows with no temp
weather_df['TEMP'].replace({'****': None},inplace =True)
weather_df['TEMP'] = pd.to_numeric(weather_df['TEMP'])

In [47]:
weather_df['MIN'].replace({'***': None},inplace =True)
weather_df['MAX'].replace({'***': None},inplace =True)
weather_df['DATE'] = weather_df['DATE'].astype('datetime64[ns]')
weather_df

,USAF,WBAN,YR--MODAHRMN,DATE,DIR,SPD,GUS,CLG,SKC,VSB,TEMP,DEWP,SLP,ALT,STP,MAX,MIN
0,724030,93738,201801000000,2018-01-01,***,0,***,722,SCT,10,14.0,6,1030,*****,1018,21,13
1,724030,93738,201801000000,2018-01-01,320,5,***,722,SCT,10,15.0,8,1030,30,1018,None,None
2,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,11.0,6,1031,30,1018,None,None
3,724030,93738,201801000000,2018-01-01,990,3,***,722,CLR,10,11.0,4,1031,30,1018,None,None
4,724030,93738,201801000000,2018-01-01,320,6,***,722,CLR,10,13.0,3,1031,30,1019,None,None
5,724030,93738,201801000000,2018-01-01,320,3,***,722,CLR,10,12.0,3,1031,30,1019,21,10
6,724030,93738,201801000000,2018-01-01,***,***,***,***,***,****,NaN,****,******,*****,******,21,None
7,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,8.0,2,1031,30,1018,15,7
8,724030,93738,201801000000,2018-01-01,***,0,***,***,***,10,8.0,2,1031,*****,1019,20,7
9,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,8.0,2,1031,30,1019,None,None
10,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,7.0,1,1031,30,1019,None,None
11,724030,93738,201801000000,2018-01-01,300,10,***,722,CLR,10,12.0,4,1031,30,1019,None,None
12,724030,93738,201801000000,2018-01-01,290,6,***,722,CLR,10,11.0,4,1031,30,1019,None,None
13,724030,93738,201801000000,2018-01-01,290,5,***,722,CLR,10,10.0,3,1032,30,1019,None,None
14,724030,93738,201801000000,2018-01-01,280,7,***,722,CLR,10,10.0,3,1033,30,1020,12,6
15,724030,93738,201801000000,2018-01-01,280,7,***,***,***,10,10.0,3,1033,*****,1021,21,6
16,724030,93738,201801000000,2018-01-01,290,8,***,722,CLR,10,12.0,4,1033,30,1020,None,None
17,724030,93738,201801000000,2018-01-01,290,15,***,722,SCT,10,15.0,5,1033,31,1021,None,None
18,724030,93738,201801000000,2018-01-01,310,15,***,722,SCT,10,17.0,5,1034,31,1021,None,None
19,724030,93738,201801000000,2018-01-01,310,14,***,722,SCT,10,19.0,4,1034,31,1022,None,None
20,724030,93738,201801000000,2018-01-01,310,18,23,722,SCT,10,19.0,2,1033,30,1021,None,None
21,724030,93738,201801000000,2018-01-01,310,16,22,49,***,10,23.0,2,1032,30,1020,23,10
22,724030,93738,201801000000,2018-01-01,310,16,***,***,BKN,10,23.0,2,1032,*****,1020,23,10
23,724030,93738,201801000000,2018-01-01,320,10,***,50,***,10,21.0,2,1032,30,1019,None,None
24,724030,93738,201801000000,2018-01-01,300,24,31,55,***,10,22.0,0,1031,30,1019,None,None
25,724030,93738,201801000000,2018-01-01,320,13,***,49,***,10,21.0,0,******,30,1019,None,None
26,724030,93738,201801000000,2018-01-01,310,17,***,50,***,10,20.0,0,1031,30,1019,None,None
27,724030,93738,201801000000,2018-01-01,300,7,***,722,SCT,10,19.0,1,1031,30,1019,None,None
28,724030,93738,201801000000,2018-01-01,310,6,***,722,SCT,10,18.0,0,1032,30,1019,None,None
29,724030,93738,201801000000,2018-01-01,320,7,***,722,CLR,10,17.0,-1,1033,30,1020,23,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12699,724030,93738,201901000000,2019-01-01,***,***,***,***,***,****,NaN,****,******,*****,******,47,None
12700,724030,93738,201901000000,2019-01-01,190,9,***,2,***,0,49.0,49,******,30,997,None,None
12701,724030,93738,201901000000,2019-01-01,190,11,***,2,***,0,50.0,50,1008,30,997,50,44
12702,724030,93738,201901000000,2019-01-01,190,11,***,***,OVC,0,50.0,50,1008,*****,997,50,37
12703,724030,93738,201901000000,2019-01-01,200,14,***,3,***,1,52.0,52,******,30,997,None,None
12704,724030,93738,201901000000,2019-01-01,210,11,***,4,***,10,54.0,54,******,30,996,None,None
12705,724030,93738,201901000000,2019-01-01,200,14,***,5,***,10,54.0,54,******,30,996,None,None
12706,724030,93738,201901000000,2019-01-01,200,13,23,5,***,10,55.0,55,1008,30,996,None,None
12707,724030,93738,201901000000,2019-01-01,190,16,***,9,***,10,57.0,56,1007,30,995,None,None
12708,724030,93738,201901000000,2019-01-01,200,14,***,11,***,10,57.0,56,******,30,995,None,None
12709,724030,93738,201901000000,2019-01-01,200,11,***,110,***,10,57.0,57,******,30,995,None,None
12710,724030,93738,201901000000,2019-01-01,210,13,***,110,***,10,58.0,57,1007,30,995,None,None
12711,724030,93738,201901000000,2019-01-01,210,10,***,160,***,10,57.0,56,1007,30,995,None,None
12712,724030,93738,201901000000,2019-01-01,200,10,***,210,***,10,57.0,56,1008,30,996,None,None
12713,724030,93738,201901000000,2019-01-01,220,10,***,230,***,10,60.0,54,1009,30,998,60,50
12714,724030,93738,201901000000,2019-01-01,220,10,***,***,BKN,10,60.0,54,1009,*****,998,None,44
12715,724030,93738,201901000000,2019-01-01,280,8,***,180,***,10,61.0,50,1010,30,999,None,None
12716,724030,93738,201901000000,2019-01-01,290,15,***,180,***,10,60.0,48,******,30,1000,None,None
12717,724030,93738,201901000000,2019-01-01,280,14,***,180,***,10,61.0,47,1012,30,1001,None,None
12718,724030,93738,201901000000,2019-01-01,300,17,***,90,***,10,59.0,46,1013,30,1002,None,None
12719,724030,93738,201901000000,2019-01-01,320,17,28,90,***,10,58.0,45,1014,30,1003,None,None
12720,724030,93738,201901000000,2019-01-01,320,23,34,90,***,10,57.0,42,1014,30,1003,None,None
12721,724030,93738,201901000000,2019-01-01,310,20,30,200,***,10,57.0,42,1016,30,1004,62,56
12722,724030,93738,201901000000,2019-01-01,310,20,***,***,BKN,10,57.0,42,1016,*****,1004,62,44
12723,724030,93738,201901000000,2019-01-01,330,17,30,200,***,10,55.0,42,1016,30,1005,None,None
12724,724030,93738,201901000000,2019-01-01,340,17,24,200,***,10,53.0,41,1018,30,1006,None,None
12725,724030,93738,201901000000,2019-01-01,330,14,***,90,***,10,51.0,39,1019,30,1008,None,None
12726,724030,93738,201901000000,2019-01-01,330,13,***,200,***,10,50.0,39,1020,30,1008,None,None
12727,724030,93738,201901000000,2019-01-01,330,15,***,200,***,10,49.0,38,1021,30,1009,None,None
12728,724030,93738,201901000000,2019-01-01,330,6,***,722,SCT,10,47.0,38,1022,30,1010,57,47

In [48]:
weather_df.dropna(axis=0, how='any', thresh=None, subset=['TEMP'], inplace=True)
weather_df

,USAF,WBAN,YR--MODAHRMN,DATE,DIR,SPD,GUS,CLG,SKC,VSB,TEMP,DEWP,SLP,ALT,STP,MAX,MIN
0,724030,93738,201801000000,2018-01-01,***,0,***,722,SCT,10,14.0,6,1030,*****,1018,21,13
1,724030,93738,201801000000,2018-01-01,320,5,***,722,SCT,10,15.0,8,1030,30,1018,None,None
2,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,11.0,6,1031,30,1018,None,None
3,724030,93738,201801000000,2018-01-01,990,3,***,722,CLR,10,11.0,4,1031,30,1018,None,None
4,724030,93738,201801000000,2018-01-01,320,6,***,722,CLR,10,13.0,3,1031,30,1019,None,None
5,724030,93738,201801000000,2018-01-01,320,3,***,722,CLR,10,12.0,3,1031,30,1019,21,10
7,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,8.0,2,1031,30,1018,15,7
8,724030,93738,201801000000,2018-01-01,***,0,***,***,***,10,8.0,2,1031,*****,1019,20,7
9,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,8.0,2,1031,30,1019,None,None
10,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,7.0,1,1031,30,1019,None,None
11,724030,93738,201801000000,2018-01-01,300,10,***,722,CLR,10,12.0,4,1031,30,1019,None,None
12,724030,93738,201801000000,2018-01-01,290,6,***,722,CLR,10,11.0,4,1031,30,1019,None,None
13,724030,93738,201801000000,2018-01-01,290,5,***,722,CLR,10,10.0,3,1032,30,1019,None,None
14,724030,93738,201801000000,2018-01-01,280,7,***,722,CLR,10,10.0,3,1033,30,1020,12,6
15,724030,93738,201801000000,2018-01-01,280,7,***,***,***,10,10.0,3,1033,*****,1021,21,6
16,724030,93738,201801000000,2018-01-01,290,8,***,722,CLR,10,12.0,4,1033,30,1020,None,None
17,724030,93738,201801000000,2018-01-01,290,15,***,722,SCT,10,15.0,5,1033,31,1021,None,None
18,724030,93738,201801000000,2018-01-01,310,15,***,722,SCT,10,17.0,5,1034,31,1021,None,None
19,724030,93738,201801000000,2018-01-01,310,14,***,722,SCT,10,19.0,4,1034,31,1022,None,None
20,724030,93738,201801000000,2018-01-01,310,18,23,722,SCT,10,19.0,2,1033,30,1021,None,None
21,724030,93738,201801000000,2018-01-01,310,16,22,49,***,10,23.0,2,1032,30,1020,23,10
22,724030,93738,201801000000,2018-01-01,310,16,***,***,BKN,10,23.0,2,1032,*****,1020,23,10
23,724030,93738,201801000000,2018-01-01,320,10,***,50,***,10,21.0,2,1032,30,1019,None,None
24,724030,93738,201801000000,2018-01-01,300,24,31,55,***,10,22.0,0,1031,30,1019,None,None
25,724030,93738,201801000000,2018-01-01,320,13,***,49,***,10,21.0,0,******,30,1019,None,None
26,724030,93738,201801000000,2018-01-01,310,17,***,50,***,10,20.0,0,1031,30,1019,None,None
27,724030,93738,201801000000,2018-01-01,300,7,***,722,SCT,10,19.0,1,1031,30,1019,None,None
28,724030,93738,201801000000,2018-01-01,310,6,***,722,SCT,10,18.0,0,1032,30,1019,None,None
29,724030,93738,201801000000,2018-01-01,320,7,***,722,CLR,10,17.0,-1,1033,30,1020,23,17
30,724030,93738,201801000000,2018-01-02,320,7,***,***,***,10,17.0,-1,1033,*****,1021,23,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12698,724030,93738,201901000000,2019-01-01,190,10,***,2,OBS,0,46.0,46,1010,30,998,46,30
12700,724030,93738,201901000000,2019-01-01,190,9,***,2,***,0,49.0,49,******,30,997,None,None
12701,724030,93738,201901000000,2019-01-01,190,11,***,2,***,0,50.0,50,1008,30,997,50,44
12702,724030,93738,201901000000,2019-01-01,190,11,***,***,OVC,0,50.0,50,1008,*****,997,50,37
12703,724030,93738,201901000000,2019-01-01,200,14,***,3,***,1,52.0,52,******,30,997,None,None
12704,724030,93738,201901000000,2019-01-01,210,11,***,4,***,10,54.0,54,******,30,996,None,None
12705,724030,93738,201901000000,2019-01-01,200,14,***,5,***,10,54.0,54,******,30,996,None,None
12706,724030,93738,201901000000,2019-01-01,200,13,23,5,***,10,55.0,55,1008,30,996,None,None
12707,724030,93738,201901000000,2019-01-01,190,16,***,9,***,10,57.0,56,1007,30,995,None,None
12708,724030,93738,201901000000,2019-01-01,200,14,***,11,***,10,57.0,56,******,30,995,None,None
12709,724030,93738,201901000000,2019-01-01,200,11,***,110,***,10,57.0,57,******,30,995,None,None
12710,724030,93738,201901000000,2019-01-01,210,13,***,110,***,10,58.0,57,1007,30,995,None,None
12711,724030,93738,201901000000,2019-01-01,210,10,***,160,***,10,57.0,56,1007,30,995,None,None
12712,724030,93738,201901000000,2019-01-01,200,10,***,210,***,10,57.0,56,1008,30,996,None,None
12713,724030,93738,201901000000,2019-01-01,220,10,***,230,***,10,60.0,54,1009,30,998,60,50
12714,724030,93738,201901000000,2019-01-01,220,10,***,***,BKN,10,60.0,54,1009,*****,998,None,44
12715,724030,93738,201901000000,2019-01-01,280,8,***,180,***,10,61.0,50,1010,30,999,None,None
12716,724030,93738,201901000000,2019-01-01,290,15,***,180,***,10,60.0,48,******,30,1000,None,None
12717,724030,93738,201901000000,2019-01-01,280,14,***,180,***,10,61.0,47,1012,30,1001,None,None
12718,724030,93738,201901000000,2019-01-01,300,17,***,90,***,10,59.0,46,1013,30,1002,None,None
12719,724030,93738,201901000000,2019-01-01,320,17,28,90,***,10,58.0,45,1014,30,1003,None,None
12720,724030,93738,201901000000,2019-01-01,320,23,34,90,***,10,57.0,42,1014,30,1003,None,None
12721,724030,93738,201901000000,2019-01-01,310,20,30,200,***,10,57.0,42,1016,30,1004,62,56
12722,724030,93738,201901000000,2019-01-01,310,20,***,***,BKN,10,57.0,42,1016,*****,1004,62,44
12723,724030,93738,201901000000,2019-01-01,330,17,30,200,***,10,55.0,42,1016,30,1005,None,None
12724,724030,93738,201901000000,2019-01-01,340,17,24,200,***,10,53.0,41,1018,30,1006,None,None
12725,724030,93738,201901000000,2019-01-01,330,14,***,90,***,10,51.0,39,1019,30,1008,None,None
12726,724030,93738,201901000000,2019-01-01,330,13,***,200,***,10,50.0,39,1020,30,1008,None,None
12727,724030,93738,201901000000,2019-01-01,330,15,***,200,***,10,49.0,38,1021,30,1009,None,None
12728,724030,93738,201901000000,2019-01-01,330,6,***,722,SCT,10,47.0,38,1022,30,1010,57,47

In [53]:
weather_mean = pd.DataFrame (weather_df.groupby(['DATE']).mean()['TEMP']).reset_index()
weather_max = pd.DataFrame (weather_df.groupby(['DATE']).max()['TEMP']).reset_index()
weather_min = pd.DataFrame (weather_df.groupby(['DATE']).min()['TEMP']).reset_index()
weather_summary = pd.merge(weather_mean, weather_max, on='DATE', how='inner')
weather_summary = pd.merge(weather_summary, weather_min, on='DATE', how='inner')
weather_summary

          DATE     TEMP_x  TEMP_y  TEMP
0   2018-01-01  14.689655    23.0   7.0
1   2018-01-02  14.517241    24.0   8.0
2   2018-01-03  15.392857    32.0   2.0
3   2018-01-04  23.868421    29.0  18.0
4   2018-01-05  14.285714    19.0  10.0
5   2018-01-06  12.714286    18.0   8.0
6   2018-01-07  12.206897    24.0   0.0
7   2018-01-08  24.575758    33.0  18.0
8   2018-01-09  34.411765    49.0  23.0
9   2018-01-10  31.928571    43.0  22.0
10  2018-01-11  46.470588    61.0  38.0
11  2018-01-12  63.276596    70.0  58.0
12  2018-01-13  46.327273    65.0  24.0
13  2018-01-14  19.678571    26.0  14.0
14  2018-01-15  19.600000    30.0  11.0
15  2018-01-16  28.903226    39.0  21.0
16  2018-01-17  26.675676    35.0  21.0
17  2018-01-18  27.068966    46.0  16.0
18  2018-01-19  34.071429    53.0  19.0
19  2018-01-20  37.214286    61.0  21.0
20  2018-01-21  43.482759    62.0  29.0
21  2018-01-22  55.107143    65.0  44.0
22  2018-01-23  56.350000    62.0  48.0
23  2018-01-24  41.857143    48.0  36.0
24  2018-01-25  34.250000    41.0  30.0
25  2018-01-26  31.178571    47.0  20.0
26  2018-01-27  43.571429    60.0  26.0
27  2018-01-28  52.027027    57.0  48.0
28  2018-01-29  44.133333    48.0  41.0
29  2018-01-30  32.571429    43.0  25.0
..         ...        ...     ...   ...
336 2018-12-03  52.030303    58.0  45.0
337 2018-12-04  40.785714    47.0  37.0
338 2018-12-05  33.000000    38.0  29.0
339 2018-12-06  34.750000    41.0  28.0
340 2018-12-07  35.678571    40.0  29.0
341 2018-12-08  27.750000    36.0  19.0
342 2018-12-09  30.535714    33.0  29.0
343 2018-12-10  31.214286    38.0  26.0
344 2018-12-11  29.607143    43.0  20.0
345 2018-12-12  33.000000    43.0  24.0
346 2018-12-13  40.607143    51.0  30.0
347 2018-12-14  38.733333    44.0  29.0
348 2018-12-15  45.384615    52.0  42.0
349 2018-12-16  44.777778    52.0  40.0
350 2018-12-17  44.375000    55.0  39.0
351 2018-12-18  39.678571    45.0  36.0
352 2018-12-19  33.857143    50.0  23.0
353 2018-12-20  36.722222    41.0  27.0
354 2018-12-21  58.547619    66.0  41.0
355 2018-12-22  46.303030    54.0  42.0
356 2018-12-23  38.214286    46.0  29.0
357 2018-12-24  41.482759    46.0  37.0
358 2018-12-25  36.214286    42.0  30.0
359 2018-12-26  31.964286    48.0  22.0
360 2018-12-27  36.571429    49.0  25.0
361 2018-12-28  45.387755    51.0  42.0
362 2018-12-29  44.750000    54.0  37.0
363 2018-12-30  38.750000    46.0  33.0
364 2018-12-31  39.660000    46.0  30.0
365 2019-01-01  53.333333    61.0  44.0

[366 rows x 4 columns]

In [55]:
weather_summary = weather_summary.rename(columns={'TEMP_x': 'AVG', 'TEMP_y': 'MAX', 'TEMP': 'MIN'})
weather_summary

          DATE        AVG   MAX   MIN
0   2018-01-01  14.689655  23.0   7.0
1   2018-01-02  14.517241  24.0   8.0
2   2018-01-03  15.392857  32.0   2.0
3   2018-01-04  23.868421  29.0  18.0
4   2018-01-05  14.285714  19.0  10.0
5   2018-01-06  12.714286  18.0   8.0
6   2018-01-07  12.206897  24.0   0.0
7   2018-01-08  24.575758  33.0  18.0
8   2018-01-09  34.411765  49.0  23.0
9   2018-01-10  31.928571  43.0  22.0
10  2018-01-11  46.470588  61.0  38.0
11  2018-01-12  63.276596  70.0  58.0
12  2018-01-13  46.327273  65.0  24.0
13  2018-01-14  19.678571  26.0  14.0
14  2018-01-15  19.600000  30.0  11.0
15  2018-01-16  28.903226  39.0  21.0
16  2018-01-17  26.675676  35.0  21.0
17  2018-01-18  27.068966  46.0  16.0
18  2018-01-19  34.071429  53.0  19.0
19  2018-01-20  37.214286  61.0  21.0
20  2018-01-21  43.482759  62.0  29.0
21  2018-01-22  55.107143  65.0  44.0
22  2018-01-23  56.350000  62.0  48.0
23  2018-01-24  41.857143  48.0  36.0
24  2018-01-25  34.250000  41.0  30.0
25  2018-01-26  31.178571  47.0  20.0
26  2018-01-27  43.571429  60.0  26.0
27  2018-01-28  52.027027  57.0  48.0
28  2018-01-29  44.133333  48.0  41.0
29  2018-01-30  32.571429  43.0  25.0
..         ...        ...   ...   ...
336 2018-12-03  52.030303  58.0  45.0
337 2018-12-04  40.785714  47.0  37.0
338 2018-12-05  33.000000  38.0  29.0
339 2018-12-06  34.750000  41.0  28.0
340 2018-12-07  35.678571  40.0  29.0
341 2018-12-08  27.750000  36.0  19.0
342 2018-12-09  30.535714  33.0  29.0
343 2018-12-10  31.214286  38.0  26.0
344 2018-12-11  29.607143  43.0  20.0
345 2018-12-12  33.000000  43.0  24.0
346 2018-12-13  40.607143  51.0  30.0
347 2018-12-14  38.733333  44.0  29.0
348 2018-12-15  45.384615  52.0  42.0
349 2018-12-16  44.777778  52.0  40.0
350 2018-12-17  44.375000  55.0  39.0
351 2018-12-18  39.678571  45.0  36.0
352 2018-12-19  33.857143  50.0  23.0
353 2018-12-20  36.722222  41.0  27.0
354 2018-12-21  58.547619  66.0  41.0
355 2018-12-22  46.303030  54.0  42.0
356 2018-12-23  38.214286  46.0  29.0
357 2018-12-24  41.482759  46.0  37.0
358 2018-12-25  36.214286  42.0  30.0
359 2018-12-26  31.964286  48.0  22.0
360 2018-12-27  36.571429  49.0  25.0
361 2018-12-28  45.387755  51.0  42.0
362 2018-12-29  44.750000  54.0  37.0
363 2018-12-30  38.750000  46.0  33.0
364 2018-12-31  39.660000  46.0  30.0
365 2019-01-01  53.333333  61.0  44.0

[366 rows x 4 columns]

In [64]:
filepath='2018_lunarClean.csv'
lunar_df = pd.read_csv(filepath)
lunar_df = lunar_df.rename(columns={'Date': 'DATE'})
lunar_df['DATE'] = lunar_df['DATE'].astype('datetime64[ns]')

In [65]:
weather_data = pd.merge(weather_summary, lunar_df, on='DATE', how='inner')

In [66]:
weather_data.to_csv('2018_weather_complete.csv", index=True, header=True)