In [3]:
import pandas as pd
import numpy as py
import datetime as dt

In [4]:
# defining the file path
filepath = "2018weatherdata_csv.csv"
filepath

In [ ]:
# Open the file
weather_df = pd.read_csv(filepath)

In [5]:
weather_df.head()

,USAF,WBAN,YR--MODAHRMN,DATE,DIR,SPD,GUS,CLG,SKC,L,...,SLP,ALT,STP,MAX,MIN,PCP01,PCP06,PCP24,PCPXX,SD
0,724030,93738,201801000000,2018-01-01,***,0,***,722,SCT,*,...,1030,*****,1018,21,13,*****,0,*****,*****,**
1,724030,93738,201801000000,2018-01-01,320,5,***,722,SCT,*,...,1030,30,1018,***,***,0,*****,*****,*****,**
2,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,*,...,1031,30,1018,***,***,0,*****,*****,*****,**
3,724030,93738,201801000000,2018-01-01,990,3,***,722,CLR,*,...,1031,30,1018,***,***,0,*****,*****,*****,**
4,724030,93738,201801000000,2018-01-01,320,6,***,722,CLR,*,...,1031,30,1019,***,***,0,*****,*****,*****,**

In [6]:
# Drop columns with no data
del weather_df['L']
del weather_df['M']
del weather_df['H']
del weather_df['MW']
del weather_df['MW_1']
del weather_df['MW_2']
del weather_df['MW_3']
del weather_df['AW']
del weather_df['AW_4']
del weather_df['AW_5']
del weather_df['AW_6']
del weather_df['W']
del weather_df['PCP01']
del weather_df['PCP06']
del weather_df['PCP24']
del weather_df['PCPXX']
del weather_df['SD']

In [7]:
weather_df.head()

,USAF,WBAN,YR--MODAHRMN,DATE,DIR,SPD,GUS,CLG,SKC,VSB,TEMP,DEWP,SLP,ALT,STP,MAX,MIN
0,724030,93738,201801000000,2018-01-01,***,0,***,722,SCT,10,14,6,1030,*****,1018,21,13
1,724030,93738,201801000000,2018-01-01,320,5,***,722,SCT,10,15,8,1030,30,1018,***,***
2,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,11,6,1031,30,1018,***,***
3,724030,93738,201801000000,2018-01-01,990,3,***,722,CLR,10,11,4,1031,30,1018,***,***
4,724030,93738,201801000000,2018-01-01,320,6,***,722,CLR,10,13,3,1031,30,1019,***,***

In [16]:
# Drop the rows with no temp
#weather_df['TEMP'] = weather_df['TEMP'].str.replace('****','')
weather_df['TEMP'].replace({'****': None},inplace =True)
weather_df

,USAF,WBAN,YR--MODAHRMN,DATE,DIR,SPD,GUS,CLG,SKC,VSB,TEMP,DEWP,SLP,ALT,STP,MAX,MIN
0,724030,93738,201801000000,2018-01-01,***,0,***,722,SCT,10,14,6,1030,*****,1018,21,13
1,724030,93738,201801000000,2018-01-01,320,5,***,722,SCT,10,15,8,1030,30,1018,***,***
2,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,11,6,1031,30,1018,***,***
3,724030,93738,201801000000,2018-01-01,990,3,***,722,CLR,10,11,4,1031,30,1018,***,***
4,724030,93738,201801000000,2018-01-01,320,6,***,722,CLR,10,13,3,1031,30,1019,***,***
5,724030,93738,201801000000,2018-01-01,320,3,***,722,CLR,10,12,3,1031,30,1019,21,10
6,724030,93738,201801000000,2018-01-01,***,***,***,***,***,****,,****,******,*****,******,21,***
7,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,8,2,1031,30,1018,15,7
8,724030,93738,201801000000,2018-01-01,***,0,***,***,***,10,8,2,1031,*****,1019,20,7
9,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,8,2,1031,30,1019,***,***
10,724030,93738,201801000000,2018-01-01,***,0,***,722,CLR,10,7,1,1031,30,1019,***,***
11,724030,93738,201801000000,2018-01-01,300,10,***,722,CLR,10,12,4,1031,30,1019,***,***
12,724030,93738,201801000000,2018-01-01,290,6,***,722,CLR,10,11,4,1031,30,1019,***,***
13,724030,93738,201801000000,2018-01-01,290,5,***,722,CLR,10,10,3,1032,30,1019,***,***
14,724030,93738,201801000000,2018-01-01,280,7,***,722,CLR,10,10,3,1033,30,1020,12,6
15,724030,93738,201801000000,2018-01-01,280,7,***,***,***,10,10,3,1033,*****,1021,21,6
16,724030,93738,201801000000,2018-01-01,290,8,***,722,CLR,10,12,4,1033,30,1020,***,***
17,724030,93738,201801000000,2018-01-01,290,15,***,722,SCT,10,15,5,1033,31,1021,***,***
18,724030,93738,201801000000,2018-01-01,310,15,***,722,SCT,10,17,5,1034,31,1021,***,***
19,724030,93738,201801000000,2018-01-01,310,14,***,722,SCT,10,19,4,1034,31,1022,***,***
20,724030,93738,201801000000,2018-01-01,310,18,23,722,SCT,10,19,2,1033,30,1021,***,***
21,724030,93738,201801000000,2018-01-01,310,16,22,49,***,10,23,2,1032,30,1020,23,10
22,724030,93738,201801000000,2018-01-01,310,16,***,***,BKN,10,23,2,1032,*****,1020,23,10
23,724030,93738,201801000000,2018-01-01,320,10,***,50,***,10,21,2,1032,30,1019,***,***
24,724030,93738,201801000000,2018-01-01,300,24,31,55,***,10,22,0,1031,30,1019,***,***
25,724030,93738,201801000000,2018-01-01,320,13,***,49,***,10,21,0,******,30,1019,***,***
26,724030,93738,201801000000,2018-01-01,310,17,***,50,***,10,20,0,1031,30,1019,***,***
27,724030,93738,201801000000,2018-01-01,300,7,***,722,SCT,10,19,1,1031,30,1019,***,***
28,724030,93738,201801000000,2018-01-01,310,6,***,722,SCT,10,18,0,1032,30,1019,***,***
29,724030,93738,201801000000,2018-01-01,320,7,***,722,CLR,10,17,-1,1033,30,1020,23,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12699,724030,93738,201901000000,2019-01-01,***,***,***,***,***,****,,****,******,*****,******,47,***
12700,724030,93738,201901000000,2019-01-01,190,9,***,2,***,0,49,49,******,30,997,***,***
12701,724030,93738,201901000000,2019-01-01,190,11,***,2,***,0,50,50,1008,30,997,50,44
12702,724030,93738,201901000000,2019-01-01,190,11,***,***,OVC,0,50,50,1008,*****,997,50,37
12703,724030,93738,201901000000,2019-01-01,200,14,***,3,***,1,52,52,******,30,997,***,***
12704,724030,93738,201901000000,2019-01-01,210,11,***,4,***,10,54,54,******,30,996,***,***
12705,724030,93738,201901000000,2019-01-01,200,14,***,5,***,10,54,54,******,30,996,***,***
12706,724030,93738,201901000000,2019-01-01,200,13,23,5,***,10,55,55,1008,30,996,***,***
12707,724030,93738,201901000000,2019-01-01,190,16,***,9,***,10,57,56,1007,30,995,***,***
12708,724030,93738,201901000000,2019-01-01,200,14,***,11,***,10,57,56,******,30,995,***,***
12709,724030,93738,201901000000,2019-01-01,200,11,***,110,***,10,57,57,******,30,995,***,***
12710,724030,93738,201901000000,2019-01-01,210,13,***,110,***,10,58,57,1007,30,995,***,***
12711,724030,93738,201901000000,2019-01-01,210,10,***,160,***,10,57,56,1007,30,995,***,***
12712,724030,93738,201901000000,2019-01-01,200,10,***,210,***,10,57,56,1008,30,996,***,***
12713,724030,93738,201901000000,2019-01-01,220,10,***,230,***,10,60,54,1009,30,998,60,50
12714,724030,93738,201901000000,2019-01-01,220,10,***,***,BKN,10,60,54,1009,*****,998,***,44
12715,724030,93738,201901000000,2019-01-01,280,8,***,180,***,10,61,50,1010,30,999,***,***
12716,724030,93738,201901000000,2019-01-01,290,15,***,180,***,10,60,48,******,30,1000,***,***
12717,724030,93738,201901000000,2019-01-01,280,14,***,180,***,10,61,47,1012,30,1001,***,***
12718,724030,93738,201901000000,2019-01-01,300,17,***,90,***,10,59,46,1013,30,1002,***,***
12719,724030,93738,201901000000,2019-01-01,320,17,28,90,***,10,58,45,1014,30,1003,***,***
12720,724030,93738,201901000000,2019-01-01,320,23,34,90,***,10,57,42,1014,30,1003,***,***
12721,724030,93738,201901000000,2019-01-01,310,20,30,200,***,10,57,42,1016,30,1004,62,56
12722,724030,93738,201901000000,2019-01-01,310,20,***,***,BKN,10,57,42,1016,*****,1004,62,44
12723,724030,93738,201901000000,2019-01-01,330,17,30,200,***,10,55,42,1016,30,1005,***,***
12724,724030,93738,201901000000,2019-01-01,340,17,24,200,***,10,53,41,1018,30,1006,***,***
12725,724030,93738,201901000000,2019-01-01,330,14,***,90,***,10,51,39,1019,30,1008,***,***
12726,724030,93738,201901000000,2019-01-01,330,13,***,200,***,10,50,39,1020,30,1008,***,***
12727,724030,93738,201901000000,2019-01-01,330,15,***,200,***,10,49,38,1021,30,1009,***,***
12728,724030,93738,201901000000,2019-01-01,330,6,***,722,SCT,10,47,38,1022,30,1010,57,47